# Generated by Django 5.2.17 on 2026-08-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('TASK_ASSIGNED', 'Task Assigned'), ('COMMENT', 'Comment')], default='GENERAL', max_length=30),
        ),
    ]
